export const visualTheme = {
  colors: {
    ink950: '#0D1418',
    metalSurface: '#182328',
    paperText: '#DDD4BD',
    mutedText: '#9F9A89',
    crystalGlow: '#68D5D0',
    sealVermilion: '#E05A42',
    fireGyeol: '#FFAD42',
    danger: '#CF505C',
    success: '#74C995',
    info: '#72AEE8',
  },
  typography: {
    displayFamily: '"Gowun Batang", serif',
    bodyFamily: '"SUIT Variable", sans-serif',
    dataFamily: '"IBM Plex Mono", monospace',
    labelSize: '11px',
    bodySize: '13px',
    emphasizedSize: '15px',
    panelTitleSize: '18px',
    sectionTitleSize: '24px',
    displaySize: '36px',
  },
  spacing: {
    '2xs': '2px',
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    '2xl': '48px',
    '3xl': '64px',
  },
  radii: {
    sm: '2px',
    md: '4px',
    lg: '6px',
    full: '9999px',
  },
  panel: {
    inset: '16px',
    mobileGutter: '32px',
    paddingBlock: '8px',
    paddingInline: '16px',
    borderWidth: '1px',
    playerWidth: '262px',
    targetWidth: '362px',
    resourceWidth: '282px',
    debugWidth: '212px',
    mobileTargetTop: '104px',
  },
  motion: {
    glowPeriodMs: 2_400,
    microMs: 100,
    shortMs: 200,
  },
} as const;

export type VisualTheme = typeof visualTheme;

export function themeCssVariables(theme: VisualTheme = visualTheme): string {
  const variables: ReadonlyArray<readonly [string, string]> = [
    ['--rd-ink-950', theme.colors.ink950],
    ['--rd-metal-surface', theme.colors.metalSurface],
    ['--rd-paper-text', theme.colors.paperText],
    ['--rd-muted-text', theme.colors.mutedText],
    ['--rd-crystal-glow', theme.colors.crystalGlow],
    ['--rd-seal-vermilion', theme.colors.sealVermilion],
    ['--rd-fire-gyeol', theme.colors.fireGyeol],
    ['--rd-danger', theme.colors.danger],
    ['--rd-success', theme.colors.success],
    ['--rd-info', theme.colors.info],
    ['--rd-font-display', theme.typography.displayFamily],
    ['--rd-font-body', theme.typography.bodyFamily],
    ['--rd-font-data', theme.typography.dataFamily],
    ['--rd-type-label-size', theme.typography.labelSize],
    ['--rd-type-body-size', theme.typography.bodySize],
    ['--rd-type-emphasized-size', theme.typography.emphasizedSize],
    ['--rd-type-panel-title-size', theme.typography.panelTitleSize],
    ['--rd-type-section-title-size', theme.typography.sectionTitleSize],
    ['--rd-type-display-size', theme.typography.displaySize],
    ['--rd-space-2xs', theme.spacing['2xs']],
    ['--rd-space-xs', theme.spacing.xs],
    ['--rd-space-sm', theme.spacing.sm],
    ['--rd-space-md', theme.spacing.md],
    ['--rd-space-lg', theme.spacing.lg],
    ['--rd-space-xl', theme.spacing.xl],
    ['--rd-space-2xl', theme.spacing['2xl']],
    ['--rd-space-3xl', theme.spacing['3xl']],
    ['--rd-radius-sm', theme.radii.sm],
    ['--rd-radius-md', theme.radii.md],
    ['--rd-radius-lg', theme.radii.lg],
    ['--rd-radius-full', theme.radii.full],
    ['--rd-panel-inset', theme.panel.inset],
    ['--rd-panel-mobile-gutter', theme.panel.mobileGutter],
    ['--rd-panel-padding-block', theme.panel.paddingBlock],
    ['--rd-panel-padding-inline', theme.panel.paddingInline],
    ['--rd-panel-border-width', theme.panel.borderWidth],
    ['--rd-panel-player-width', theme.panel.playerWidth],
    ['--rd-panel-target-width', theme.panel.targetWidth],
    ['--rd-panel-resource-width', theme.panel.resourceWidth],
    ['--rd-panel-debug-width', theme.panel.debugWidth],
    ['--rd-panel-mobile-target-top', theme.panel.mobileTargetTop],
    ['--rd-motion-micro', `${theme.motion.microMs}ms`],
    ['--rd-motion-short', `${theme.motion.shortMs}ms`],
  ];
  return variables
    .map(([variable, value]) => `${variable}:${value}`)
    .join(';');
}
